services:
  postgres:
    image: postgres:16-alpine
    container_name: cv-postgres
    environment:
      POSTGRES_DB: compras_ventas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - cv_postgres_data:/var/lib/postgresql/data
    networks:
      - cv-network 
    restart: unless-stopped
  spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-spring-api
    ports:
      - "8089:8089"
    networks:
      - cv-network
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  cv_postgres_data:
    driver: local
networks:
  cv-network:
    driver: bridge